"""empty message

Revision ID: 441f408ac549
Revises: cc45bac48866
Create Date: 2021-10-21 15:01:20.379125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '441f408ac549'
down_revision = 'cc45bac48866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredients_info')
    op.add_column('ingredients', sa.Column('amount_unit', sa.Float(), nullable=False))
    op.add_column('ingredients', sa.Column('recipe_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ingredients', 'recipes', ['recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'recipe_id')
    op.drop_column('ingredients', 'amount_unit')
    op.create_table('ingredients_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount_unit', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name='ingredients_info_ingredient_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='ingredients_info_recipe_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ingredients_info_pkey')
    )
    # ### end Alembic commands ###
